const interfaceConfig = {
  APP_NAME: "LearnUp Platform",
  AUDIO_LEVEL_PRIMARY_COLOR: "rgba(255,255,255,0.4)",
  AUDIO_LEVEL_SECONDARY_COLOR: "rgba(255,255,255,0.2)",
  AUTO_PIN_LATEST_SCREEN_SHARE: "remote-only",
  BRAND_WATERMARK_LINK: "",
  CLOSE_PAGE_GUEST_HINT: false,
  CONNECTION_INDICATOR_AUTO_HIDE_ENABLED: true,
  CONNECTION_INDICATOR_AUTO_HIDE_TIMEOUT: 5000,
  CONNECTION_INDICATOR_DISABLED: false,
  DEFAULT_BACKGROUND: "#474747",
  DEFAULT_LOCAL_DISPLAY_NAME: "me",
  DEFAULT_LOGO_URL: "",
  DEFAULT_REMOTE_DISPLAY_NAME: "Fellow Student",
  DEFAULT_WELCOME_PAGE_LOGO_URL: "",
  DISABLE_DOMINANT_SPEAKER_INDICATOR: false,
  DISABLE_FOCUS_INDICATOR: false,
  DISABLE_JOIN_LEAVE_NOTIFICATIONS: false,
  DISABLE_PRESENCE_STATUS: false,
  DISABLE_RINGING: false,
  DISABLE_TRANSCRIPTION_SUBTITLES: false,
  DISABLE_VIDEO_BACKGROUND: false,
  DISPLAY_WELCOME_FOOTER: false,
  DISPLAY_WELCOME_PAGE_ADDITIONAL_CARD: false,
  DISPLAY_WELCOME_PAGE_CONTENT: false,
  DISPLAY_WELCOME_PAGE_TOOLBAR_ADDITIONAL_CONTENT: false,
  ENABLE_DIAL_OUT: false,
  ENABLE_FEEDBACK_ANIMATION: false,
  FILM_STRIP_MAX_HEIGHT: 120,
  GENERATE_ROOMNAMES_ON_WELCOME_PAGE: true,
  HIDE_INVITE_MORE_HEADER: true,
  HIDE_KICK_BUTTON_FOR_GUESTS: false,
  INITIAL_TOOLBAR_TIMEOUT: 20000,
  JITSI_WATERMARK_LINK: "",
  LANG_DETECTION: true,
  LIVE_STREAMING_HELP_LINK: "",
  LOCAL_THUMBNAIL_RATIO: 16 / 9,
  MAXIMUM_ZOOMING_COEFFICIENT: 1.3,
  MOBILE_APP_PROMO: false,
  MOBILE_DOWNLOAD_LINK_ANDROID: "",
  MOBILE_DOWNLOAD_LINK_F_DROID: "",
  MOBILE_DOWNLOAD_LINK_IOS: "",
  NATIVE_APP_NAME: "LearnUp",
  OPTIMAL_BROWSERS: ["chrome", "chromium", "firefox", "safari", "edge"],
  POLICY_LOGO: null,
  PROVIDER_NAME: "LearnUp",
  RECENT_LIST_ENABLED: false,
  REMOTE_THUMBNAIL_RATIO: 1,
  SETTINGS_SECTIONS: [
    "devices",
    "language",
    "moderator",
    "profile",
    "calendar",
    "sounds",
  ],
  SHOW_BRAND_WATERMARK: false,
  SHOW_CHROME_EXTENSION_BANNER: false,
  SHOW_DEEP_LINKING_IMAGE: false,
  SHOW_JITSI_WATERMARK: false,
  SHOW_POWERED_BY: false,
  SHOW_PROMOTIONAL_CLOSE_PAGE: false,
  SHOW_WATERMARK_FOR_GUESTS: false,
  SUPPORT_URL: "",
  TOOLBAR_ALWAYS_VISIBLE: false,
  TOOLBAR_BUTTONS: [
    "microphone",
    "camera",
    "closedcaptions",
    "desktop",
    "embedmeeting",
    "fullscreen",
    "fodeviceselection",
    "hangup",
    "profile",
    "chat",
    "recording",
    "livestreaming",
    "etherpad",
    "sharedvideo",
    "shareaudio",
    "settings",
    "raisehand",
    "videoquality",
    "filmstrip",
    "invite",
    "feedback",
    "stats",
    "shortcuts",
    "tileview",
    "select-background",
    "download",
    "help",
    "mute-everyone",
    "mute-video-everyone",
    "security",
  ],
  TOOLBAR_TIMEOUT: 4000,
  UNSUPPORTED_BROWSERS: [],
  VERTICAL_FILMSTRIP: true,
  VIDEO_LAYOUT_FIT: "both",
  VIDEO_QUALITY_LABEL_DISABLED: false,
  DISABLE_POLLS: false,
  DISABLE_REACTIONS: false,
};
